export const FETCH_REQUEST = 'FETCH_REQUEST';
export const FETCH_SUCCESS = 'FETCH_SUCCESS';
export const FETCH_FAIL = 'FETCH_FAIL';

export const FETCH_PRODUCT_START = 'FETCH_PRODUCT_START';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';

export const CARD_ADD_ITEM_START = 'CARD_ADD_ITEM_START';
export const CARD_ADD_ITEM_SUCCESS = 'CARD_ADD_ITEM_SUCCESS';
export const CARD_ADD_ITEM_FAIL = 'CARD_ADD_ITEM_FAIL';

export const CARD_REMOVE_ITEM_START = 'CARD_REMOVE_ITEM_START';
export const CARD_REMOVE_ITEM_SUCCESS = 'CARD_REMOVE_ITEM_SUCCESS';
